apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocks-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blocks
  template:
    metadata:
      labels:
        app: blocks
    spec:
      containers:
      - name: blocks
        image: 375387671478.dkr.ecr.us-east-2.amazonaws.com/blocks57:blocks-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: blocks-svc
  labels:
    app: blocks-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: blocks
  type: LoadBalancer