# name: Deploy App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
     
      # - name: Terraform Init
      #   working-directory: terraform
      #   run: terraform init

      # - name: Terraform Plan
      #   working-directory: terraform
      #   run: terraform plan

      # - name: Terraform Apply
      #   working-directory: terraform
      #   run: terraform apply -auto-approve

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and push Docker image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         run: |
#           docker build -t blocks .
#           docker tag blocks $ECR_REGISTRY/blocks:blocks-latest
#           docker push $ECR_REGISTRY/blocks:blocks-latest

#       - name: Setup Ansible
#         uses: ansible/ansible@v2.9.6
#         with:
#           ansible-version: 2.9.6

#       - name: Deploy to Kubernetes
#         env:
#           KUBECONFIG: ${{ secrets.KUBECONFIG }}
#         working-directory: deployment
#         run: ansible-playbook ansible-deployment.yml
